INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("mouthwash","health",17,"01/08/2018","02/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("charger","electronics",26,"02/08/2018","03/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("socks","clothing",76,"03/08/2018","04/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("guitar","music",30,"04/08/2018","05/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("basket","home",111,"05/08/2018","06/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("coat","clothing",169,"06/08/2018","07/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("watch","clothing",150,"07/08/2018","08/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("desk","home",399,"08/08/2018","09/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("suspenders","clothing",27,"09/08/2018","10/08/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("robot","electronics",79,"10/08/2018","11/08/2018");

INSERT INTO users (name, age) VALUES ("John",74);
INSERT INTO users (name, age) VALUES ("Janice",70);
INSERT INTO users (name, age) VALUES ("Kevin",55);
INSERT INTO users (name, age) VALUES ("Karen",60);
INSERT INTO users (name, age) VALUES ("Larry",26);
INSERT INTO users (name, age) VALUES ("Linda",78);
INSERT INTO users (name, age) VALUES ("Mark",39);
INSERT INTO users (name, age) VALUES ("Melinda",61);
INSERT INTO users (name, age) VALUES ("Orion",88);
INSERT INTO users (name, age) VALUES ("Ophelia",82);
INSERT INTO users (name, age) VALUES ("Paul",29);
INSERT INTO users (name, age) VALUES ("Pam",70);
INSERT INTO users (name, age) VALUES ("Quentin",93);
INSERT INTO users (name, age) VALUES ("Queen",75);
INSERT INTO users (name, age) VALUES ("Robert",75);
INSERT INTO users (name, age) VALUES ("Rhonda",59);
INSERT INTO users (name, age) VALUES ("Steven",62);
INSERT INTO users (name, age) VALUES ("Sharona",82);
INSERT INTO users (name, age) VALUES ("Thomas",64);
INSERT INTO users (name, age) VALUES ("Tina",52);

INSERT INTO pledges (amount, user_id, project_id) VALUES (25,13,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75,4,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (96,5,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90,9,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (85,1,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (27,4,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (53,9,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (44,12,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40,2,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (27,9,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (86,5,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (78,10,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (29,9,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,15,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (61,14,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (32,12,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90,5,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (71,20,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (42,6,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60,18,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (72,16,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (61,17,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (89,14,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (66,19,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (31,15,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (17,13,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (74,20,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14,11,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65,12,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (88,18,10);
